services:
  privana-services:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ENV_FILE=.env.mainnet
    image: "ghcr.io/oasisprotocol/privana-services@sha256:02f67dbfd35fd71d8e04ca16d79e91c277f0f0c564a25cab89650c9d3da89994"
    platform: linux/amd64
    environment:
      - LIQUIDITY_PROVIDER_SECRET_KEY
      - POOL_ADMIN_SECRET_KEY
      - EARN_POOL_SECRET_KEY
      - SAPPHIRE_RPC_HEADERS
      - BASE_RPC_URL
      - ETHEREUM_RPC_URL
      - HYPEREVM_RPC_URL
      - LIFI_API_KEY
      - COINGECKO_API_KEY
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - data:/app/data
    ports:
      - "8000:8000"
    annotations:
      net.oasis.proxy.ports.8000.custom_domain: services.privana.finance
    restart: on-failure

volumes:
  data:
