services:
  privana-services:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ENV_FILE=.env.mainnet
    image: "ghcr.io/oasisprotocol/privana-services@sha256:6f1edd8fff3adaff3c144cda3de76d8be65370d1241d431f3bc04472e2df5240"
    platform: linux/amd64
    environment:
      - LIQUIDITY_PROVIDER_SECRET_KEY
      - POOL_ADMIN_SECRET_KEY
      - EARN_POOL_SECRET_KEY
      - SAPPHIRE_RPC_HEADERS
      - BASE_RPC_URL
      - LIFI_API_KEY
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - data:/app/data
    ports:
      - "8000:8000"
    annotations:
      net.oasis.proxy.ports.8000.custom_domain: services.privana.finance
    restart: on-failure

volumes:
  data:
